### PR TITLE
libcpprestsdk: fix building as a static library

### PR DESCRIPTION
**Pull request by ffontaine**
Use pkg-config to find OpenSSL. This will automatically find any
dependent libraries and put them in the correct order for linking.

Signed-off-by: Adam Duskett <aduskett@gmail.com>
[Retrieved from:
https://git.buildroot.net/buildroot/tree/package/libcpprestsdk/0001-libcpprestsdk-fix-building-as-a-static-library.patch]
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by ffontaine** [comment]
I'm resending a new PR for this change as #688 was not merged and we have this patch in buildroot to fix static build.

**Comment by BillyONeal** [comment]
Looks like legitimate breaks in Ubuntu and macOS from this change that would need to be resolved before I can merge this.

**Comment by ffontaine** [comment]
OK, I'll fix those issues and update the PR.

**Comment by BillyONeal** [comment]
As an FYI, CI is on the floor because the echo.websockets.org SSL cert expired; you can ignore that failure :)

**Comment by ffontaine** [comment]
OK, so main issue is that patch is adding a mandatory dependency on pkgconfig, I will make it optional.

**Comment by BillyONeal** [comment]
Looks like they finally renewed that cert, merged to let Pipelines try again; thanks for your contribution!

**Comment by BillyONeal** [comment]
Hmm looking at this again it looks like the vcpkg part is still on the floor:

```
FAILED: : && /usr/bin/c++  -std=c++11 -fno-strict-aliasing -g  -rdynamic Release/tests/common/TestRunner/CMakeFiles/test_runner.dir/test_runner.cpp.o Release/tests/common/TestRunner/CMakeFiles/test_runner.dir/test_module_loader.cpp.o  -o Release/Binaries/test_runner  -Wl,-rpath,/home/vsts/work/1/s/build.debug/Release/Binaries -lpthread Release/Binaries/libunittestpp.so -ldl Release/Binaries/libcpprest.so.2.10 -lpthread -lssl -lcrypto ../vcpkg/installed/x64-linux/debug/lib/libboost_random.a ../vcpkg/installed/x64-linux/debug/lib/libboost_system.a ../vcpkg/installed/x64-linux/debug/lib/libboost_thread.a ../vcpkg/installed/x64-linux/debug/lib/libboost_filesystem.a ../vcpkg/installed/x64-linux/debug/lib/libboost_chrono.a ../vcpkg/installed/x64-linux/debug/lib/libboost_atomic.a ../vcpkg/installed/x64-linux/debug/lib/libboost_date_time.a ../vcpkg/installed/x64-linux/debug/lib/libboost_regex.a && :
Release/Binaries/libcpprest.so.2.10: undefined reference to `ENGINE_cleanup'
Release/Binaries/libcpprest.so.2.10: undefined reference to `SSLv3_method'
Release/Binaries/libcpprest.so.2.10: undefined reference to `SSLv23_method'
Release/Binaries/libcpprest.so.2.10: undefined reference to `SSLv23_client_method'
Release/Binaries/libcpprest.so.2.10: undefined reference to `SSLv3_client_method'
Release/Binaries/libcpprest.so.2.10: undefined reference to `ERR_free_strings'
Release/Binaries/libcpprest.so.2.10: undefined reference to `SSL_load_error_strings'
Release/Binaries/libcpprest.so.2.10: undefined reference to `SSL_library_init'
Release/Binaries/libcpprest.so.2.10: undefined reference to `SSLv3_server_method'
Release/Binaries/libcpprest.so.2.10: undefined reference to `OPENSSL_add_all_algorithms_noconf'
Release/Binaries/libcpprest.so.2.10: undefined reference to `EVP_cleanup'
Release/Binaries/libcpprest.so.2.10: undefined reference to `SSLv23_server_method'
Release/Binaries/libcpprest.so.2.10: undefined reference to `sk_num'
Release/Binaries/libcpprest.so.2.10: undefined reference to `CRYPTO_set_locking_callback'
Release/Binaries/libcpprest.so.2.10: undefined reference to `sk_value'
Release/Binaries/libcpprest.so.2.10: undefined reference to `CRYPTO_num_locks'
Release/Binaries/libcpprest.so.2.10: undefined reference to `CRYPTO_cleanup_all_ex_data'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Pull request closed without merging**
