### PR TITLE
Use C++11 synchronization classes under macOS too

### PR DESCRIPTION
**Pull request by vadz**
There doesn't seem to be any reason to prefer using Boost libraries to
standard C++ classes under macOS, so use the latter ones unconditionally
on this platform too, just as it was already done for the other Unix
systems.

This notably avoids dependencies on the compiled Boost libraries, which
don't have to be compiled before building C++ REST SDK any more.

---

See #1338. The tests do pass, of course:
```
% ./test_runner *_test.dylib
Loaded libhttpclient_test.dylib...
Loaded libhttplistener_test.dylib...
Loaded libjson_test.dylib...
Loaded libpplx_test.dylib...
Loaded libstreams_test.dylib...
Loaded liburi_test.dylib...
Loaded libutils_test.dylib...
Loaded libwebsocketsclient_test.dylib...
=== Running tests from: <static> ===
=== Running tests from: libhttpclient_test.dylib ===
...
All test cases PASSED

Finished running all 837 tests.
Took 26974.2ms
```

### CODE REVIEW

**Comment by BillyONeal** [comment]
Thanks for your contribution!

(I believe we still have the boost dependency for asio)

**Comment by vadz** [comment]
> Thanks for your contribution!

Thanks for merging it so quickly!
 
> (I believe we still have the boost dependency for asio)

Yes, but this one would be a bit more difficult to get rid of :-/ Also, Boost.ASIO is a header-only library, so it's much less of a problem in practice (e.g. there is no danger of conflicting with Boost libraries installed by Homebrew or anything like that).

**Comment by BillyONeal** [comment]
>Thanks for merging it so quickly!

Occasionally I swing by and merge a bunch of PRs, and the most recent time is around now, so it worked out :)

>Boost.ASIO is a header-only library, so it's much less of a problem in practice (e.g. there is no danger of conflicting with Boost libraries installed by Homebrew or anything like that).

I'm not familiar with MacOS's dynamic linking scheme, but if it's anything like POSIX's this is no help because the asio symbol names leak into our .so / .dylib.

**Comment by vadz** [comment]
> I'm not familiar with MacOS's dynamic linking scheme, but if it's anything like POSIX's this is no help because the asio symbol names leak into our .so / .dylib.

Thanks to your comment I've just discovered that the library doesn't seem to use visibility correctly (i.e. hidden by default, visible for public symbols). This is indeed a serious problem, but luckily shouldn't be difficult to fix, considering that it already uses `_ASYNCRTIMP` which seems like it could be repurposed for this too (although I'm not totally certain as the macro name is not really clear). I'll try to make a PR for this too, although not today.

**Pull request merged**
