### PR TITLE
Fix thread not joined

### LINKED ISSUE #32: Double delete in wspp_callback_client destructor?
Hi, 

We have this weird issue that users report crashes, but so far all my tries to reproduce it failed.  The crash seems to be happening in the destructor of the websocket callback client and the stacktraces are always the same, here is one for example:

Thread 64 Crashed:: Dispatch queue: com.apple.root.default-qos
0   libsystem_kernel.dylib            0x00007fff960630ae __pthread_kill + 10
1   libsystem_pthread.dylib           0x00007fff96cc6500 pthread_kill + 90
2   libsystem_c.dylib                 0x00007fff9a11c41b __abort + 145
3   libsystem_c.dylib                 0x00007fff9a11c38a abort + 144
4   libc++abi.dylib                   0x00007fff8bc52f81 abort_message + 257
5   libc++abi.dylib                   0x00007fff8bc7896a default_terminate_handler() + 46
6   com.cisco.SparkMacDesktop         0x000000010261ad09 CLSTerminateHandler() + 270
7   libc++abi.dylib                   0x00007fff8bc7619e std::__terminate(void (_)()) + 8
8   libc++abi.dylib                   0x00007fff8bc7622d std::terminate() + 77
9   libcpprest.2.7.dylib              0x00000001033b1ba9 web::websockets::client::details::wspp_callback_client::~wspp_callback_client() + 889
10  libc++.1.dylib                    0x00007fff90411cb8 std::__1::__shared_weak_count::__release_shared() + 44
11  com.cisco.SparkMacDesktop         0x000000010275ba4f MercuryManager::_websocketConnect(int) + 1705
12  com.cisco.SparkMacDesktop         0x0000000102675e75 std::__1::__function::__func<pplx::details::_MakeVoidToUnitFunc(std::__1::function<void ()> const&)::'lambda'(), std::__1::allocator<pplx::details::_MakeVoidToUnitFunc(std::__1::function<void ()> const&)::'lambda'()>, unsigned char ()>::operator()() + 13
13  com.cisco.SparkMacDesktop         0x00000001027619f9 pplx::details::_PPLTaskHandle<unsigned char, pplx::task<unsigned char>::_InitialTaskHandle<void, MercuryManager::websocketConnect(int)::$_0, pplx::details::_TypeSelectorNoAsync>, pplx::details::_TaskProcHandle>::invoke() const + 265
14  com.cisco.SparkMacDesktop         0x00000001026508f3 pplx::details::_TaskProcHandle::_RunChoreBridge(void_) + 19
15  libdispatch.dylib                 0x00007fff95f123c3 _dispatch_client_callout + 8
16  libdispatch.dylib                 0x00007fff95f16253 _dispatch_root_queue_drain + 1890
17  libdispatch.dylib                 0x00007fff95f15ab8 _dispatch_worker_thread3 + 91
18  libsystem_pthread.dylib           0x00007fff96cc34f2 _pthread_wqthread + 1129
19  libsystem_pthread.dylib           0x00007fff96cc1375 start_wqthread + 13

Now, the interesting bit is that i see from the Casablanca code that some engineer might have run into this issue before because there seems to be a specific attempt to "handle" this:

...
     switch (m_state) {
        case DESTROYED:
            // This should be impossible
            std::abort();
...

(I am not fully sure this actually works cause if the object is indeed dead then accessing m_state might be a bad idea already, but anyway, that's not the point I am trying to make here). 

Based on the stacktrace and the code in ws_client_wspp.cpp it looks like a smoking gun: someone tries to double delete the object and the hard coded abort() is getting fired. 

Now, as much as we can ever be sure, I am pretty-pretty sure that we, the consuming app, is not doing this double delete. We create a unique pointer to a Web socket callback client and when we get the close handler invoked (set up via set_close_handler), for example if I lose network,  then we create a new PPL task, wait a bit and attempt to restore the websocket connection. The way we do that is that we create a brand new callback client (with make_unique) and replace the existing member field with this new pointer. At this point the old callback client - now in CLOSED state - is released and its destructor is called. 

I simply see no C++ way how can the destructor can be invoked twice. Do you guys have any idea what's going on here? I presume there were some issues in this area and that's why the codepath is there in the destructor with abort?

Regards,
Gergely

### PR DESCRIPTION
**Pull request by whoan**
I run into a **std::terminate issue** on Linux and I found there's a race condition between the creation of the thread that starts ASIO io_service, and the actual assignation of the thread object to `m_thread`. The new thread can try to connect and call *fail_handler* before the thread object is assigned. In this scenario, *fail_handler* will not join `m_thread` as it is still not joinable.

I modified the template method `connect_impl` in _src/websockets/client/ws_client_wspp.cpp_ to add some delay and reproduce the issue instead of using `gdb` but notice you can find easier to do it with said debugger. These are the modifications:

```c++
        auto tmpThread = std::thread([&client]() {
#if defined(__ANDROID__)
            crossplat::get_jvm_env();
#endif
            client.run();
#if defined(__ANDROID__)
            crossplat::JVM.load()->DetachCurrentThread();
#endif

#if OPENSSL_VERSION_NUMBER < 0x10100000L || defined(LIBRESSL_VERSION_NUMBER)
            // OpenSSL stores some per thread state that never will be cleaned up until
            // the dll is unloaded. If static linking, like we do, the state isn't cleaned up
            // at all and will be reported as leaks.
            // See http://www.openssl.org/support/faq.html#PROG13
            ERR_remove_thread_state(nullptr);
#endif
        });
        // my delay HERE
        std::this_thread::sleep_for(std::chrono::seconds(1));
        m_thread = std::move(tmpThread);
```

And with the following snippet I could reproduce the not joined thread:

```c++
#include <iostream>
#include <thread>
#include <pplx/pplxtasks.h>
#include <cpprest/ws_client.h>

// this is to avoid a data race in the scheduler creation reported by Google's thread sanitizer
auto scheduler = pplx::get_ambient_scheduler();

void handleTerminate() {
  std::cerr << "Unhandled exception or thread not joined\n";
  quick_exit(EXIT_FAILURE);
}

int main() {
  std::set_terminate(handleTerminate);
  auto ws = web::websockets::client::websocket_callback_client();
  try {
    ws.connect("ws://an_invalid_host").wait();
  } catch (const std::exception& ex) {
    std::cerr << "Ws connection error: " << ex.what() << std::endl;
  }
  return 0;
}
```

--------------

To test the changes in this PR, you can use the custom lib code (with the delay) but with the corresponding locks. If you run the snippet again, you will see the problem is gone.

If you want a more realistic scenario, I reproduced the problem in an application which creates lots of `websocket_callback_client`s at the same time and all of them fail at connecting to the endpoint.

--------------

This PR might fix #32 and #701

### CODE REVIEW

**Comment by BillyONeal** [comment]
I'm not sure why the CLA bot was happy with your other PR but not this one?

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Comment by bin0101** [comment]
Hi @BillyONeal, it's a great fix! We are also encountering the std::terminate issue on windows. Do you think there may be other case which cause missing calling the m_thread::join()? If so, will it be good idea to add a guard in ~wspp_callback_client(), to check m_thread joinable?

**Comment by whoan** [comment]
Hi @bin0101. Notice that a thread not joined is not the only reason to trigger [`std::terminate`](https://en.cppreference.com/w/cpp/error/terminate). Check the link to see possible causes.

A common scenario (mis)using pplx tasks is to have unhandled exceptions. Something like this could help to find the reason of the `std::terminate` call:

```c++
void handleTerminate() {
  try {
    if (!std::current_exception()) {
      throw int();  // throw anything different than std::exception here
    }
    std::rethrow_exception(std::current_exception());
  } catch (const std::exception& ex) {
    std::cerr << "Unhandled exception: " << ex.what() << std::endl;
  } catch (...) {
    std::cerr << "A thread might not be joined" << std::endl;
  }
  quick_exit(EXIT_FAILURE);
}

std::set_terminate(handleTerminate);
```

**Comment by bin0101** [comment]
@BillyONeal thanks for your explanation, but my point is the problem that the thread not joined may have different case. Your current PR fix one of the cases, but I am afraid there are other case. So I suggest that we just add a thread joinable check in ~wspp_callback_client() to avoid crash due to such case.

**Pull request merged**
