### PR TITLE
pplx-doc typo fixes

### LINKED ISSUE #189: Documentation Typo
http://microsoft.github.io/cpprestsdk/classpplx_1_1task.html

As listed it states:

pplx::task< _ReturnType > Class Template Reference

However, the < _ReturnType > is described as "_ResultType" as written in the description as follows:

The Parallel Patterns Library (PPL) task class. A task object represents work that can be executed asynchronously, and concurrently with other tasks and parallel work produced by parallel algorithms in the Concurrency Runtime. It produces a result of type _ResultType

Is this a typo?

### PR DESCRIPTION
**Pull request by msk4862**
Closes #189 

@BillyONeal @ras0219-msft please review the documentation typo fixes.

### CODE REVIEW

**Comment by garethsb-sony** [comment]
Better to fix these in the source, e.g. https://github.com/microsoft/cpprestsdk/blob/44c491889ddbcfca963aa54e175d81f0eade058d/Release/include/pplx/pplxtasks.h#L3225.

**Comment by msk4862** [comment]
@garethsb-sony but is it safe to change source files?
Like can it break any dependencies?

**Comment by garethsb-sony** [comment]
Surely better to fix the docs in their source in the C++ comments and then regenerate the ghpages HTML, which seems to have been done with Doxygen. Otherwise we'd lose your changes when the docs were regenerated. Not sure whether the Microsoft owners are running Doxygen as a CI step, or whether they trigger that manually.

**Comment by msk4862** [comment]
@garethsb-sony Okay, I didn't knew about Doxygen, I will make changes in the source docs also.
Thanks.

**Comment by msk4862** [comment]
@garethsb-sony @BillyONeal @ras0219-msft  I should also change result_type to return_type, right? like in this one
https://github.com/microsoft/cpprestsdk/blob/44c491889ddbcfca963aa54e175d81f0eade058d/Release/include/pplx/pplxtasks.h#L3245

**Comment by garethsb-sony** [comment]
Unlikely, unless you're looking to change code rather than documentation.

**Comment by msk4862** [comment]
Okay.

**Comment by msk4862** [comment]
@garethsb-sony But like in this one, I think it should be _ReturnType instead of _ResultType https://github.com/microsoft/cpprestsdk/blob/44c491889ddbcfca963aa54e175d81f0eade058d/Release/include/pplx/pplxtasks.h#L2677

**Comment by garethsb-sony** [comment]
It certainly shouldn't be changed in isolation!

The public interface of `pplx::task` and its associated classes is their `result_type`. The fact that much of the internals use `_ReturnType` as the template parameter name is an implementation detail. Moreover the fact that just a few of the classes use `_ResultType` for no good reason I can see, is probably just history/multiple authorship.

Using `ResultType` instead of `ReturnType` almost everywhere (not in some of the function-return-type helpers) would probably be easier to read, but personally I wouldn't recommend making that change just for the sake of it.

**Comment by msk4862** [comment]
okay, Thanks!

**Comment by BillyONeal** [comment]
Closing this for the reasons you've enumerated above; please feel to open a new PR with the doxygen changes, and reopen this one with regenerated doxygen output.

I'm not actually sure how to *run* doxygen to regenerate the docs, @garethsb-sony are you willing to help @msk4862 with that?

**Comment by garethsb-sony** [comment]
@BillyONeal I don't know. There is a doxygen configuration file at Release/public_apis_doxyfile, added by @stgates back in 2014, but it actually looks like **ghpages** haven't been updated since 2015.

Are Microsoft interested in bringing in a small number of additional external maintainers for this project, to triage the continually growing number of reported issues and potentially to support things like CI generation of ghpages, etc.?

**Comment by BillyONeal** [comment]
@garethsb-sony Unfortunately this project is on 'life support' (like less than 1/4 head) at this time. We're keeping the lights on in case we have some reason to pick it up in the future, but I think we have settled on the answer 'libcurl just wins for most use cases and is the de-facto industry standard.' The primary differentiating feature of the task-based asynchrony isn't super important for HTTP clients, and many of the environments like IoT that might want a native HTTP client also need a C client. (Not because we believe C is actually better for that, but because the IoT community has fallen to FUD)

**Comment by garethsb-sony** [comment]
@BillyONeal that's... disappointing. For C++ programmers, libcurl seems like a lowest common denominator. It, like many other libraries, doesn't seem to include server-side components. Having both HTTP and WebSocket, both client and server (acknowledging your previous statement of concerns on the latter), has been a big factor. While we might wish for better separation in cpprestsdk between `pplx`, `json` and `http`, I haven't come across a cross-platform C++ library that offers more out-of-the-box. I think the continuous drip of new (though often flawed) issues shows you have a user-base that wants to be engaged, and the smaller number of thoughtful issues and PRs shows there are at least a few developers who would like to contribute more.

**Pull request closed without merging**
