### PR TITLE
Show found version of openssl (cmake UNIX)

### PR DESCRIPTION
**Pull request by c72578**
This is an addition to commit cb7ca74. A message is added for cmake
UNIX target systems, which shows the version of **`openssl`** found by
`pkg_search_module()`. Furthermore, the minimum required version of 1.0.0
is added to `pkg_search_module()` like in the subsequent
`find_package(OpenSSL 1.0.0 REQUIRED)`.

Example of the cmake output including the message:
```console
  -- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3")
  -- Checking for one of the modules 'openssl>=1.0.0'
  -- Found openssl version 1.1.1d on system
  -- Performing Test _SSL_LEAK_SUPPRESS_AVAILABLE
```

### CODE REVIEW

**Comment by c72578** [comment]
Here are examples from the CI Pipelines here (build logs from Ubuntu_1804_Apt):

1.) Before (commit 18212a2):
https://dev.azure.com/vclibs/cpprestsdk/_build/results?buildId=2739&view=logs&j=0c23b9b9-8125-5329-483e-69ee393d5a90&t=7a3446bd-29fa-52ba-c6cc-d413baf39e0e&l=1517
```console
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'openssl'
-- Performing Test _SSL_LEAK_SUPPRESS_AVAILABLE
```
2.) Using PR #1398:

https://dev.azure.com/vclibs/cpprestsdk/_build/results?buildId=2764&view=logs&j=0c23b9b9-8125-5329-483e-69ee393d5a90&t=7a3446bd-29fa-52ba-c6cc-d413baf39e0e&l=1473
```console
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'openssl>=1.0.0'
-- Found openssl version 1.1.1 on system
-- Performing Test _SSL_LEAK_SUPPRESS_AVAILABLE
```

**Comment by garethsb-sony** [comment]
@c72578, do you know the answer to #1388?

**Comment by c72578** [comment]
@garethsb-sony I had a look at #1388 and I will probably add this to the PR here:
```diff
diff --git a/Release/cmake/cpprest_find_openssl.cmake b/Release/cmake/cpprest_find_openssl.cmake
index 93336636..db10c829 100644
--- a/Release/cmake/cpprest_find_openssl.cmake
+++ b/Release/cmake/cpprest_find_openssl.cmake
@@ -48,7 +48,7 @@ function(cpprest_find_openssl)
       pkg_search_module(OPENSSL openssl)
     endif()
     if(OPENSSL_FOUND)
-      target_link_libraries(cpprest PRIVATE ${OPENSSL_LDFLAGS})
+      target_link_libraries(cpprest INTERFACE ${OPENSSL_LDFLAGS})
     else()
       find_package(OpenSSL 1.0.0 REQUIRED)
     endif()
```

**Comment by garethsb-sony** [comment]
Great!

**Comment by c72578** [comment]
It looks like commit https://github.com/microsoft/cpprestsdk/commit/cb7ca74e5f3bdbde363ed4ddb5655e76931397bd should be reverted for now.
See reported issues: https://github.com/microsoft/cpprestsdk/issues/1378#issuecomment-620105565 and #1388

So, I will close this PR.

**Pull request closed without merging**
