### PR TITLE
Define __STDC_FORMAT_MACROS when it hasn't been defined to avoid duplicate define error.

### PR DESCRIPTION
**Pull request by sighingnow**

### CODE REVIEW

**Comment by sighingnow** [comment]
The macro `__STDC_FORMAT_MACROS` may comes from command line args, or outer CMakeLists.txt when cpprestsdk is used as a submodule.

**Comment by sighingnow** [comment]
Polite ping /cc @BillyONeal @garethsb-sony

**Comment by BillyONeal** [comment]
@barcharcraz is the new @BillyONeal to this repo

**Comment by sighingnow** [comment]
Thank you Billy.

Then /cc @barcharcraz 😆

**Comment by barcharcraz** [comment]
lg2m

**Pull request merged**
