### PR TITLE
Dockerization

### PR DESCRIPTION
**Pull request by ChrisCates**
A long long time ago.
I made an issue #982...

There was no real interest in the issue... I figured I might as well try to get a conversation rolling in regards to this integration.

Right now, I've just added a boilerplate Dockerfile for Ubuntu `bionic`.
However, I'm sure there are several things we need to consider before integrating it into `master`.

1. Azure Pipelines, how should this be integrated? The current Dockerfile does not compile from source and cannot run test cases. However, a Dockerfile that compiles from source can most certainly run test cases in Azure Pipelines. Perhaps for repository based versions of the library a regression test case with cmake or make that tries to include a cpprestsdk header file would suffice.

2. It does not compile from source, right now it downloads from the Ubuntu repositories. Perhaps a Dockerfile that compiles from source would be useful for certain users. 

3. Dockerfiles for other operating systems may be useful such as Alpine, Windows and so forth.

If there are any other considerations, feel free to add them as a comment and start a discussion.

### CODE REVIEW

**Comment by BillyONeal** [comment]
Unfortunately I am unsure how to meaningfully review this; given that it's getting cpprestsdk from an externally maintained source, it doesn't seem to be appropriate to be part of this particular repository.

Note that the cpprestsdk team at MS is completely uninvolved with the apt package produced for Debian consumed by Ubuntu derivatives. I think that might be maintained by @LocutusOfBorg ?

**Comment by ChrisCates** [comment]
No worries. In this case should we be using Docker to pull from a Microsoft
maintained package manager instead?

**Comment by LocutusOfBorg** [comment]
I can help on Ubuntu side if you want... e.g. I added in my ppa the last stable version compiled for ubuntu 18.04
https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/locutusofborg-ppa

You can steal from there if you want!

but in any case, a docker should pull something stable, while you are talking about continuous build... I think there are two different things here to do, e.g. we can use travis for continuous build and docker to have a stable image

**Comment by ChrisCates** [comment]
@LocutusOfBorg, I can make sure to download from a PPA that can stay consistent and stable. However, I think @BillyONeal, might want it to be Azure pipelines instead of Travis to keep the CI consistent.

@BillyONeal, in terms of implementation. If the above is okay, I can update the PR to work with either Azure or Travis.

For now, it would be fine to just have a Docker Container that just uses Ubuntu, since, I've had no problems running this same container on both Windows and Mac OS. If needed, other OS image Docker containers would make sense if other users with specific edge cases might need them... But seems like extra legwork plus regression testing for no real reason.

**Comment by BillyONeal** [comment]
@ChrisCates I don't know anything about docker containers or why you would want cpprestsdk, and only cpprestsdk, in a container. (It seems like it's a library and you would need to deploy something else in the container)

Given that the cpprestsdk project isn't officially going out of our way to support them, I don't know where the most appropriate place is; only that that place isn't here.

**Pull request closed without merging**
