### PR TITLE
Add the missing ssl::context callback in websocket_client_config

### PR DESCRIPTION
**Pull request by garethsb-sony**
In order to be able to set up certificates. Exactly the same use case as http_client_config and borrowing heavily from http_client implementation.

### CODE REVIEW

**Comment by garethsb-sony** [comment]
@BillyONeal I don't think the reported CI failures are actually related to this PR, am I right?

**Comment by BillyONeal** [comment]
I think I managed to kick off another try: https://dev.azure.com/vclibs/cpprestsdk/_build/results?buildId=306

Will keep you posted.

**Comment by garethsb-sony** [comment]
Thanks. It looks like the same two platforms failed:

* Ubuntu 16.04 Vcpkg - which seems to be unable to find Boost?
* Android - which fails building Boost with "Undefined or not supported Android NDK version: 19.0"

**Comment by BillyONeal** [comment]
Something is borked with Pipelines and vcpkg right now; I reported to vcpkg folks and will keep you posted.

**Comment by garethsb-sony** [comment]
Thanks. It'd be great to get #1049 and #1051 tested and into master.

**Comment by BillyONeal** [comment]
Looks like Pipelines is off the floor and your change works. Do want to add a test case for this? (This is small enough that I'll merge it without a test added but we're liable to break the feature on you again without it)

**Comment by BillyONeal** [comment]
I guess we can always add that test later. Thanks for your contribution!

**Pull request merged**
