### PR TITLE
Add API to set the number of threads in the asio thread pool.

### PR DESCRIPTION
**Pull request by BillyONeal**
Alternative resolution of https://github.com/Microsoft/cpprestsdk/pull/775

### CODE REVIEW

**Comment by katemamba** [comment]
This function allows an application (in their main function) to initialize the cpprestsdk
 threadpool with a custom threadcount.
Can you point to example how to use this function in main with sample example.

**Comment by BillyONeal** [comment]
Before touching anything related to cpprestsdk you should just be able to do:

crossplat::threadpool::initialize_with_threads(pick a number)

Note that this only has an effect on platforms where cpprestsdk is manually creating a fixed number of threads; for example on Windows we use the system thread pool and it owns thread creation policy.

**Comment by katemamba** [comment]
Could you give a sample, how this threadpool needs to be attached to cpprestsdk . Also its a static method, I am unsure where this needs to be done in application main()?

 `#include <pplx/threadpool.h>

using namespace web;
using namespace crossplat;
int main(int argc, const char *argv[])
{
    crossplat::threadpool::initialize_with_threads(500);`

This results in /home/kate/workspace/test/casablancatest/src/ms_main.cpp:13: error: *'initialize_with_threads’ is not a member of ‘crossplat::threadpool’*
How does restsdk ensure that it uses this new threadpool everytime.
I am using linux ubuntu_16.04 and default threads are limited to 40.

**Comment by katemamba** [comment]
Nevermind, got it. Pretty useful feature. Thanks for this.

**Pull request merged**
