### PR TITLE
Fixing .then to work with movable-only types

### PR DESCRIPTION
**Pull request by AntonBikineev**
This seems to fix the following reported issue:
https://casablanca.codeplex.com/workitem/418

### CODE REVIEW

**Comment by ras0219-msft** [comment]
First, sincerest apologies for taking so long to review this PR. This is a complex PR for us because on Windows we default to the in-box copy of PPL in order to maximize compatibility with other applications. By accepting this PR, we'll be diverging in capabilities (so code that works in *nix won't work on windows), which isn't something we take lightly. However, after consideration, the benefits of enabling move-only types here (at least on posix) definitely outweighs the detriments of differing platform capabilities.

TLDR; sorry for taking so long, we do want to merge this in!

However, when attempting to build this on Ubuntu 14.04 with gcc-4.8, I'm getting the following error:
```
In file included from /usr/include/x86_64-linux-gnu/c++/4.8/bits/c++allocator.h:33:0,
                 from /usr/include/c++/4.8/bits/allocator.h:46,
                 from /usr/include/c++/4.8/vector:61,
                 from /home/casaserv/cpprestsdk/Release/tests/functional/pplx/pplx_test/stdafx.h:31,
                 from /home/casaserv/cpprestsdk/Release/tests/functional/pplx/pplx_test/pplxtask_tests.cpp:23:
/usr/include/c++/4.8/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62; _Args = {pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>&}; _Tp = tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62]’:
/usr/include/c++/4.8/bits/alloc_traits.h:254:4:   required from ‘static typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type std::allocator_traits<_Alloc>::_S_construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62; _Args = {pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>&}; _Alloc = std::allocator<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>; typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type = void]’
/usr/include/c++/4.8/bits/alloc_traits.h:393:57:   required from ‘static decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) std::allocator_traits<_Alloc>::construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62; _Args = {pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>&}; _Alloc = std::allocator<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>; decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) = <type error>]’
/usr/include/c++/4.8/bits/shared_ptr_base.h:400:38:   required from ‘std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>&}; _Tp = tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62; _Alloc = std::allocator<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]’
/usr/include/c++/4.8/ext/new_allocator.h:120:4:   required from ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::_Sp_counted_ptr_inplace<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62, std::allocator<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>, (__gnu_cxx::_Lock_policy)2u>; _Args = {const std::allocator<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>, pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>&}; _Tp = std::_Sp_counted_ptr_inplace<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62, std::allocator<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>, (__gnu_cxx::_Lock_policy)2u>]’
/usr/include/c++/4.8/bits/alloc_traits.h:254:4:   required from ‘static typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type std::allocator_traits<_Alloc>::_S_construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = std::_Sp_counted_ptr_inplace<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62, std::allocator<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>, (__gnu_cxx::_Lock_policy)2u>; _Args = {const std::allocator<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>, pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>&}; _Alloc = std::allocator<std::_Sp_counted_ptr_inplace<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62, std::allocator<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>, (__gnu_cxx::_Lock_policy)2u> >; typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type = void]’
/usr/include/c++/4.8/bits/alloc_traits.h:393:57:   [ skipping 8 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/c++/4.8/functional:1946:51:   required from ‘static bool std::_Function_base::_Base_manager<_Functor>::_M_manager(std::_Any_data&, const std::_Any_data&, std::_Manager_operation) [with _Functor = pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>]’
/usr/include/c++/4.8/functional:2460:19:   required from ‘std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>; <template-parameter-2-2> = void; _Res = char; _ArgTypes = {int}]’
/home/casaserv/cpprestsdk/Release/include/pplx/pplxtasks.h:3900:147:   required from ‘void pplx::task<_Type>::_ContinuationTaskHandle<_InternalReturnType, _ContinuationReturnType, _Function, _IsTaskBased, _TypeSelection>::_Continue(std::false_type, pplx::details::_TypeSelectorNoAsync) const [with _InternalReturnType = int; _ContinuationReturnType = char; _Function = tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62; _IsTaskBased = std::integral_constant<bool, false>; _TypeSelection = pplx::details::_TypeSelectorNoAsync; _ReturnType = int; std::false_type = std::integral_constant<bool, false>]’
/home/casaserv/cpprestsdk/Release/include/pplx/pplxtasks.h:3873:55:   required from ‘void pplx::task<_Type>::_ContinuationTaskHandle<_InternalReturnType, _ContinuationReturnType, _Function, _IsTaskBased, _TypeSelection>::_Perform() const [with _InternalReturnType = int; _ContinuationReturnType = char; _Function = tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62; _IsTaskBased = std::integral_constant<bool, false>; _TypeSelection = pplx::details::_TypeSelectorNoAsync; _ReturnType = int]’
/home/casaserv/cpprestsdk/Release/include/pplx/pplxtasks.h:1648:17:   required from ‘void pplx::details::_PPLTaskHandle<_ReturnType, _DerivedTaskHandle, _BaseTaskHandle>::invoke() const [with _ReturnType = char; _DerivedTaskHandle = pplx::task<int>::_ContinuationTaskHandle<int, char, tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62, std::integral_constant<bool, false>, pplx::details::_TypeSelectorNoAsync>; _BaseTaskHandle = pplx::details::_ContinuationTaskHandleBase]’
/home/casaserv/cpprestsdk/Release/tests/functional/pplx/pplx_test/pplxtask_tests.cpp:1961:3:   required from here


/usr/include/c++/4.8/ext/new_allocator.h:120:4: error: no matching function for call to ‘tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62::__lambda62(pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>&)’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^


/usr/include/c++/4.8/ext/new_allocator.h:120:4: note: candidate is:
/home/casaserv/cpprestsdk/Release/tests/functional/pplx/pplx_test/pplxtask_tests.cpp:317:41: note: constexpr tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62::<lambda>(tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62&&)
     auto f = task.then([a = std::move(a)](int) { return 'c'; });
                                         ^
/home/casaserv/cpprestsdk/Release/tests/functional/pplx/pplx_test/pplxtask_tests.cpp:317:41: note:   no known conversion for argument 1 from ‘pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62>’ to ‘tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::__lambda62&&’
make[3]: *** [tests/functional/pplx/pplx_test/CMakeFiles/pplx_test.dir/pplxtask_tests.cpp.o] Error 1
make[2]: *** [tests/functional/pplx/pplx_test/CMakeFiles/pplx_test.dir/all] Error 2
make[1]: *** [tests/functional/pplx/pplx_test/CMakeFiles/pplx_test.dir/rule] Error 2
make: *** [pplx_test] Error 2
```

We will also need to disable the test you added on windows; this should be as simple as an `#ifndef _MSC_VER`.

It isn't obvious how to fix the Linux error, so if you can handle that issue we can easily patch up the disable-test-on-Windows after the merge.

**Comment by AntonBikineev** [comment]
@ras0219-msft,

**Comment by ras0219-msft** [comment]
I'm still getting an issue on Ubuntu. Here's some system information:
```
$ g++-4.8 -v
Using built-in specs.
COLLECT_GCC=g++-4.8
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1)

$ uname -a
Linux casa-ubuntu64-a 3.16.0-60-generic #80~14.04.1-Ubuntu SMP Wed Jan 20 13:37:48 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Here's the error:
```
In file included from /usr/include/x86_64-linux-gnu/c++/4.8/bits/c++allocator.h:33:0,
                 from /usr/include/c++/4.8/bits/allocator.h:46,
                 from /usr/include/c++/4.8/vector:61,
                 from /home/casaserv/cpprestsdk/Release/tests/functional/pplx/pplx_test/stdafx.h:31,
                 from /home/casaserv/cpprestsdk/Release/tests/functional/pplx/pplx_test/pplxtask_tests.cpp:23:
/usr/include/c++/4.8/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A; _Args = {pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>&}; _Tp = tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A]’:
/usr/include/c++/4.8/bits/alloc_traits.h:254:4:   required from ‘static typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type std::allocator_traits<_Alloc>::_S_construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A; _Args = {pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>&}; _Alloc = std::allocator<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>; typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type = void]’
/usr/include/c++/4.8/bits/alloc_traits.h:393:57:   required from ‘static decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) std::allocator_traits<_Alloc>::construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A; _Args = {pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>&}; _Alloc = std::allocator<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>; decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) = <type error>]’
/usr/include/c++/4.8/bits/shared_ptr_base.h:400:38:   required from ‘std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>&}; _Tp = tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A; _Alloc = std::allocator<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]’
/usr/include/c++/4.8/ext/new_allocator.h:120:4:   required from ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::_Sp_counted_ptr_inplace<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A, std::allocator<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>, (__gnu_cxx::_Lock_policy)2u>; _Args = {const std::allocator<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>, pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>&}; _Tp = std::_Sp_counted_ptr_inplace<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A, std::allocator<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>, (__gnu_cxx::_Lock_policy)2u>]’
/usr/include/c++/4.8/bits/alloc_traits.h:254:4:   required from ‘static typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type std::allocator_traits<_Alloc>::_S_construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = std::_Sp_counted_ptr_inplace<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A, std::allocator<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>, (__gnu_cxx::_Lock_policy)2u>; _Args = {const std::allocator<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>, pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>&}; _Alloc = std::allocator<std::_Sp_counted_ptr_inplace<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A, std::allocator<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>, (__gnu_cxx::_Lock_policy)2u> >; typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type = void]’
/usr/include/c++/4.8/bits/alloc_traits.h:393:57:   [ skipping 8 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/c++/4.8/functional:1946:51:   required from ‘static bool std::_Function_base::_Base_manager<_Functor>::_M_manager(std::_Any_data&, const std::_Any_data&, std::_Manager_operation) [with _Functor = pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>]’
/usr/include/c++/4.8/functional:2460:19:   required from ‘std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>; <template-parameter-2-2> = void; _Res = char; _ArgTypes = {int}]’
/home/casaserv/cpprestsdk/Release/include/pplx/pplxtasks.h:3900:147:   required from ‘void pplx::task<_Type>::_ContinuationTaskHandle<_InternalReturnType, _ContinuationReturnType, _Function, _IsTaskBased, _TypeSelection>::_Continue(std::false_type, pplx::details::_TypeSelectorNoAsync) const [with _InternalReturnType = int; _ContinuationReturnType = char; _Function = tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A; _IsTaskBased = std::integral_constant<bool, false>; _TypeSelection = pplx::details::_TypeSelectorNoAsync; _ReturnType = int; std::false_type = std::integral_constant<bool, false>]’
/home/casaserv/cpprestsdk/Release/include/pplx/pplxtasks.h:3873:55:   required from ‘void pplx::task<_Type>::_ContinuationTaskHandle<_InternalReturnType, _ContinuationReturnType, _Function, _IsTaskBased, _TypeSelection>::_Perform() const [with _InternalReturnType = int; _ContinuationReturnType = char; _Function = tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A; _IsTaskBased = std::integral_constant<bool, false>; _TypeSelection = pplx::details::_TypeSelectorNoAsync; _ReturnType = int]’
/home/casaserv/cpprestsdk/Release/include/pplx/pplxtasks.h:1648:17:   required from ‘void pplx::details::_PPLTaskHandle<_ReturnType, _DerivedTaskHandle, _BaseTaskHandle>::invoke() const [with _ReturnType = char; _DerivedTaskHandle = pplx::task<int>::_ContinuationTaskHandle<int, char, tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A, std::integral_constant<bool, false>, pplx::details::_TypeSelectorNoAsync>; _BaseTaskHandle = pplx::details::_ContinuationTaskHandleBase]’
/home/casaserv/cpprestsdk/Release/tests/functional/pplx/pplx_test/pplxtask_tests.cpp:1973:3:   required from here
/usr/include/c++/4.8/ext/new_allocator.h:120:4: error: no matching function for call to ‘tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A::A(pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>&)’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
/usr/include/c++/4.8/ext/new_allocator.h:120:4: note: candidates are:
/home/casaserv/cpprestsdk/Release/tests/functional/pplx/pplx_test/pplxtask_tests.cpp:314:9: note: constexpr tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A::A(tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A&&)
         A(A&&) = default;
         ^
/home/casaserv/cpprestsdk/Release/tests/functional/pplx/pplx_test/pplxtask_tests.cpp:314:9: note:   no known conversion for argument 1 from ‘pplx::details::_NonCopyableFunctorWrapper<tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A>’ to ‘tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A&&’
/home/casaserv/cpprestsdk/Release/tests/functional/pplx/pplx_test/pplxtask_tests.cpp:313:9: note: constexpr tests::functional::PPLX::Suitepplxtask_tests::TestTestTasks_movable_then::RunImpl() const::A::A()
         A() = default;
         ^
/home/casaserv/cpprestsdk/Release/tests/functional/pplx/pplx_test/pplxtask_tests.cpp:313:9: note:   candidate expects 0 arguments, 1 provided
```

What system/compiler are you using locally?

**Comment by AntonBikineev** [comment]
@ras0219-msft I was testing with clang and libc++. I seem to fix the problem and has tested it on debian/g++-4.8/libstdc++.

**Comment by ras0219-msft** [comment]
Thank you very much for your tenacity.

**Pull request merged**
