### PR TITLE
issue 665, proposed solution

### PR DESCRIPTION
**Pull request by EdgarWahn**
- add \<project\>Config.cmake.in and \<project\>ConfigVersion.cmake.in to allow cmake to import the cppresksdk project by using find_package(\<name\> \<version\>)
- add keywords in CMakeLists.txt to produce \<project\>Config.cmake and \<project\>ConfigVersion.cmake from their .in templates
- add cmake policy CMP0048 to allow version number in project statement

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thank you for the PR!

Please retarget this against master. We do already have some of what is proposed here.

**Comment by EdgarWahn** [comment]
Noobish question... "retarget against master" means I check out the current master, apply my patches and submit the diff against what?! Sorry, just got lost.

**Comment by ras0219-msft** [comment]
Yes, please check out master and apply your patches, then submit a PR here against the master branch. Thanks!

**Comment by EdgarWahn** [comment]
@see 680, is this ok now?

**Pull request closed without merging**
