### PR TITLE
Add 'const' for consistency between extract_ member functions

### PR DESCRIPTION
**Pull request by garethsb-sony**
Very simple change, so I haven't bothered to add a test that demonstrates the current inconsistency.

### CODE REVIEW

**Comment by garethsb-sony** [comment]
CI test failures are unrelated to the PR - e.g. `bind: address already in use`

**Comment by BillyONeal** [comment]
Hmmm it looks like it is a bug that any of these were ever marked const (at least, "this can only be called once" comments suggest that the functions don't actually have const behavior). Am I missing something or shouldn't the correct fix be to remove const on the couple of places doing that?

**Comment by garethsb-sony** [comment]
Yes... I went for the change that couldn't break existing code, but removing `const` from the seven request/response member functions that have it could be the right thing to do.

**Comment by BillyONeal** [comment]
Unfortunately I don't believe I should merge this. Yes, it's inconsistent, but given that (1) this project is rarely-maintained at this point, and (2) the only correct way to fix the inconsistency is likely to break many customers, I think we should wontfix it. That is to say, making a bug we did once upon a time worse in the name of consistency doesn't seem like an improvement.

At such time we blow the dust off cpprestsdk and start making substantial investments here (so there would be a carrot to come with the stick of potential breakage) I think it would be a good idea to make the reverse change (remove const from the other extract() functions).

Thanks for your contribution anyway :)

**Pull request closed without merging**
