### PR TITLE
Update licence.txt so that it's recognized as MIT

### PR DESCRIPTION
**Pull request by xtqqczze**
* Move license.txt -> LICENSE.txt
* Update LICENSE.txt so that Github recognizes it as MIT.
* Remove the term All Rights Reserved as Microsoft no longer recommend it.

See also: https://github.com/PowerShell/PowerShell/pull/12729

### CODE REVIEW

**Comment by xtqqczze** [comment]
Failed CI appears unrelated.

**Comment by barcharcraz** [comment]
can we do just the update to make it recognized as MIT without the more substantive license change?

**Comment by xtqqczze** [comment]
@barcharcraz Please see https://github.com/microsoft/react-native-windows/issues/3933 for justification for removal of the All Rights Reserved term.

**Comment by xtqqczze** [comment]
@barcharcraz

**Pull request closed without merging**
