### PR TITLE
Fix incorrect const in reinterpret_cast (#950)

### PR DESCRIPTION
**Pull request by chris0x44**
This solves the warning causing build failure referred to in https://github.com/Microsoft/cpprestsdk/issues/950

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
I think the failure is unrelated to this change, but I can't retry it...

**Comment by chris0x44** [comment]
Yes, this failure looks odd. Any way of re-doing the check so we know that it is not related?

**Comment by BillyONeal** [comment]
The failure is indeed looks to be caused by unrelated flakiness of the http listener implementation. asan and tsan found a whole bunch of memory safety problems in the listener implementation. Luckily that thing is marked "experimental, do not use in production" but we use it to test the client.

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
